//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Aresv2.n11ProductStockService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductStockServicePortSoap11", Namespace="http://www.n11.com/ws/schemas")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSkuBasicRequest))]
    public partial class ProductStockServicePortService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductStockByProductIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductStockByProductSellerCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncreaseStockByStockIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncreaseStockByStockSellerCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncreaseStockByStockAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStockByStockIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStockByStockSellerCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAndUpdateStockByStockAttributesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProductStockServicePortService() {
            this.Url = global::Aresv2.Properties.Settings.Default.Aresv2_n11ProductStockService_ProductStockServicePortService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductStockByProductIdCompletedEventHandler GetProductStockByProductIdCompleted;
        
        /// <remarks/>
        public event GetProductStockByProductSellerCodeCompletedEventHandler GetProductStockByProductSellerCodeCompleted;
        
        /// <remarks/>
        public event IncreaseStockByStockIdCompletedEventHandler IncreaseStockByStockIdCompleted;
        
        /// <remarks/>
        public event IncreaseStockByStockSellerCodeCompletedEventHandler IncreaseStockByStockSellerCodeCompleted;
        
        /// <remarks/>
        public event IncreaseStockByStockAttributesCompletedEventHandler IncreaseStockByStockAttributesCompleted;
        
        /// <remarks/>
        public event UpdateStockByStockIdCompletedEventHandler UpdateStockByStockIdCompleted;
        
        /// <remarks/>
        public event UpdateStockByStockSellerCodeCompletedEventHandler UpdateStockByStockSellerCodeCompleted;
        
        /// <remarks/>
        public event DeleteAndUpdateStockByStockAttributesCompletedEventHandler DeleteAndUpdateStockByStockAttributesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProductStockByProductIdResponse", Namespace="http://www.n11.com/ws/schemas")]
        public GetProductStockByProductIdResponse GetProductStockByProductId([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] GetProductStockByProductIdRequest GetProductStockByProductIdRequest) {
            object[] results = this.Invoke("GetProductStockByProductId", new object[] {
                        GetProductStockByProductIdRequest});
            return ((GetProductStockByProductIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductStockByProductIdAsync(GetProductStockByProductIdRequest GetProductStockByProductIdRequest) {
            this.GetProductStockByProductIdAsync(GetProductStockByProductIdRequest, null);
        }
        
        /// <remarks/>
        public void GetProductStockByProductIdAsync(GetProductStockByProductIdRequest GetProductStockByProductIdRequest, object userState) {
            if ((this.GetProductStockByProductIdOperationCompleted == null)) {
                this.GetProductStockByProductIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductStockByProductIdOperationCompleted);
            }
            this.InvokeAsync("GetProductStockByProductId", new object[] {
                        GetProductStockByProductIdRequest}, this.GetProductStockByProductIdOperationCompleted, userState);
        }
        
        private void OnGetProductStockByProductIdOperationCompleted(object arg) {
            if ((this.GetProductStockByProductIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductStockByProductIdCompleted(this, new GetProductStockByProductIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetProductStockByProductSellerCodeResponse", Namespace="http://www.n11.com/ws/schemas")]
        public GetProductStockByProductSellerCodeResponse GetProductStockByProductSellerCode([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] GetProductStockByProductSellerCodeRequest GetProductStockByProductSellerCodeRequest) {
            object[] results = this.Invoke("GetProductStockByProductSellerCode", new object[] {
                        GetProductStockByProductSellerCodeRequest});
            return ((GetProductStockByProductSellerCodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductStockByProductSellerCodeAsync(GetProductStockByProductSellerCodeRequest GetProductStockByProductSellerCodeRequest) {
            this.GetProductStockByProductSellerCodeAsync(GetProductStockByProductSellerCodeRequest, null);
        }
        
        /// <remarks/>
        public void GetProductStockByProductSellerCodeAsync(GetProductStockByProductSellerCodeRequest GetProductStockByProductSellerCodeRequest, object userState) {
            if ((this.GetProductStockByProductSellerCodeOperationCompleted == null)) {
                this.GetProductStockByProductSellerCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductStockByProductSellerCodeOperationCompleted);
            }
            this.InvokeAsync("GetProductStockByProductSellerCode", new object[] {
                        GetProductStockByProductSellerCodeRequest}, this.GetProductStockByProductSellerCodeOperationCompleted, userState);
        }
        
        private void OnGetProductStockByProductSellerCodeOperationCompleted(object arg) {
            if ((this.GetProductStockByProductSellerCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductStockByProductSellerCodeCompleted(this, new GetProductStockByProductSellerCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("IncreaseStockByStockIdResponse", Namespace="http://www.n11.com/ws/schemas")]
        public IncreaseStockByStockIdResponse IncreaseStockByStockId([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] IncreaseStockByStockIdRequest IncreaseStockByStockIdRequest) {
            object[] results = this.Invoke("IncreaseStockByStockId", new object[] {
                        IncreaseStockByStockIdRequest});
            return ((IncreaseStockByStockIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IncreaseStockByStockIdAsync(IncreaseStockByStockIdRequest IncreaseStockByStockIdRequest) {
            this.IncreaseStockByStockIdAsync(IncreaseStockByStockIdRequest, null);
        }
        
        /// <remarks/>
        public void IncreaseStockByStockIdAsync(IncreaseStockByStockIdRequest IncreaseStockByStockIdRequest, object userState) {
            if ((this.IncreaseStockByStockIdOperationCompleted == null)) {
                this.IncreaseStockByStockIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncreaseStockByStockIdOperationCompleted);
            }
            this.InvokeAsync("IncreaseStockByStockId", new object[] {
                        IncreaseStockByStockIdRequest}, this.IncreaseStockByStockIdOperationCompleted, userState);
        }
        
        private void OnIncreaseStockByStockIdOperationCompleted(object arg) {
            if ((this.IncreaseStockByStockIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncreaseStockByStockIdCompleted(this, new IncreaseStockByStockIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("IncreaseStockByStockSellerCodeResponse", Namespace="http://www.n11.com/ws/schemas")]
        public IncreaseStockByStockSellerCodeResponse IncreaseStockByStockSellerCode([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] IncreaseStockByStockSellerCodeRequest IncreaseStockByStockSellerCodeRequest) {
            object[] results = this.Invoke("IncreaseStockByStockSellerCode", new object[] {
                        IncreaseStockByStockSellerCodeRequest});
            return ((IncreaseStockByStockSellerCodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IncreaseStockByStockSellerCodeAsync(IncreaseStockByStockSellerCodeRequest IncreaseStockByStockSellerCodeRequest) {
            this.IncreaseStockByStockSellerCodeAsync(IncreaseStockByStockSellerCodeRequest, null);
        }
        
        /// <remarks/>
        public void IncreaseStockByStockSellerCodeAsync(IncreaseStockByStockSellerCodeRequest IncreaseStockByStockSellerCodeRequest, object userState) {
            if ((this.IncreaseStockByStockSellerCodeOperationCompleted == null)) {
                this.IncreaseStockByStockSellerCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncreaseStockByStockSellerCodeOperationCompleted);
            }
            this.InvokeAsync("IncreaseStockByStockSellerCode", new object[] {
                        IncreaseStockByStockSellerCodeRequest}, this.IncreaseStockByStockSellerCodeOperationCompleted, userState);
        }
        
        private void OnIncreaseStockByStockSellerCodeOperationCompleted(object arg) {
            if ((this.IncreaseStockByStockSellerCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncreaseStockByStockSellerCodeCompleted(this, new IncreaseStockByStockSellerCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("IncreaseStockByStockAttributesResponse", Namespace="http://www.n11.com/ws/schemas")]
        public IncreaseStockByStockAttributesResponse IncreaseStockByStockAttributes([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] IncreaseStockByStockAttributesRequest IncreaseStockByStockAttributesRequest) {
            object[] results = this.Invoke("IncreaseStockByStockAttributes", new object[] {
                        IncreaseStockByStockAttributesRequest});
            return ((IncreaseStockByStockAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IncreaseStockByStockAttributesAsync(IncreaseStockByStockAttributesRequest IncreaseStockByStockAttributesRequest) {
            this.IncreaseStockByStockAttributesAsync(IncreaseStockByStockAttributesRequest, null);
        }
        
        /// <remarks/>
        public void IncreaseStockByStockAttributesAsync(IncreaseStockByStockAttributesRequest IncreaseStockByStockAttributesRequest, object userState) {
            if ((this.IncreaseStockByStockAttributesOperationCompleted == null)) {
                this.IncreaseStockByStockAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncreaseStockByStockAttributesOperationCompleted);
            }
            this.InvokeAsync("IncreaseStockByStockAttributes", new object[] {
                        IncreaseStockByStockAttributesRequest}, this.IncreaseStockByStockAttributesOperationCompleted, userState);
        }
        
        private void OnIncreaseStockByStockAttributesOperationCompleted(object arg) {
            if ((this.IncreaseStockByStockAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncreaseStockByStockAttributesCompleted(this, new IncreaseStockByStockAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateStockByStockIdResponse", Namespace="http://www.n11.com/ws/schemas")]
        public UpdateStockByStockIdResponse UpdateStockByStockId([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] UpdateStockByStockIdRequest UpdateStockByStockIdRequest) {
            object[] results = this.Invoke("UpdateStockByStockId", new object[] {
                        UpdateStockByStockIdRequest});
            return ((UpdateStockByStockIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStockByStockIdAsync(UpdateStockByStockIdRequest UpdateStockByStockIdRequest) {
            this.UpdateStockByStockIdAsync(UpdateStockByStockIdRequest, null);
        }
        
        /// <remarks/>
        public void UpdateStockByStockIdAsync(UpdateStockByStockIdRequest UpdateStockByStockIdRequest, object userState) {
            if ((this.UpdateStockByStockIdOperationCompleted == null)) {
                this.UpdateStockByStockIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStockByStockIdOperationCompleted);
            }
            this.InvokeAsync("UpdateStockByStockId", new object[] {
                        UpdateStockByStockIdRequest}, this.UpdateStockByStockIdOperationCompleted, userState);
        }
        
        private void OnUpdateStockByStockIdOperationCompleted(object arg) {
            if ((this.UpdateStockByStockIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStockByStockIdCompleted(this, new UpdateStockByStockIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UpdateStockByStockSellerCodeResponse", Namespace="http://www.n11.com/ws/schemas")]
        public UpdateStockByStockSellerCodeResponse UpdateStockByStockSellerCode([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] UpdateStockByStockSellerCodeRequest UpdateStockByStockSellerCodeRequest) {
            object[] results = this.Invoke("UpdateStockByStockSellerCode", new object[] {
                        UpdateStockByStockSellerCodeRequest});
            return ((UpdateStockByStockSellerCodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStockByStockSellerCodeAsync(UpdateStockByStockSellerCodeRequest UpdateStockByStockSellerCodeRequest) {
            this.UpdateStockByStockSellerCodeAsync(UpdateStockByStockSellerCodeRequest, null);
        }
        
        /// <remarks/>
        public void UpdateStockByStockSellerCodeAsync(UpdateStockByStockSellerCodeRequest UpdateStockByStockSellerCodeRequest, object userState) {
            if ((this.UpdateStockByStockSellerCodeOperationCompleted == null)) {
                this.UpdateStockByStockSellerCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStockByStockSellerCodeOperationCompleted);
            }
            this.InvokeAsync("UpdateStockByStockSellerCode", new object[] {
                        UpdateStockByStockSellerCodeRequest}, this.UpdateStockByStockSellerCodeOperationCompleted, userState);
        }
        
        private void OnUpdateStockByStockSellerCodeOperationCompleted(object arg) {
            if ((this.UpdateStockByStockSellerCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStockByStockSellerCodeCompleted(this, new UpdateStockByStockSellerCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteAndUpdateStockByStockAttributesResponse", Namespace="http://www.n11.com/ws/schemas")]
        public DeleteAndUpdateStockByStockAttributesResponse DeleteAndUpdateStockByStockAttributes([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.n11.com/ws/schemas")] DeleteAndUpdateStockByStockAttributesRequest DeleteAndUpdateStockByStockAttributesRequest) {
            object[] results = this.Invoke("DeleteAndUpdateStockByStockAttributes", new object[] {
                        DeleteAndUpdateStockByStockAttributesRequest});
            return ((DeleteAndUpdateStockByStockAttributesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAndUpdateStockByStockAttributesAsync(DeleteAndUpdateStockByStockAttributesRequest DeleteAndUpdateStockByStockAttributesRequest) {
            this.DeleteAndUpdateStockByStockAttributesAsync(DeleteAndUpdateStockByStockAttributesRequest, null);
        }
        
        /// <remarks/>
        public void DeleteAndUpdateStockByStockAttributesAsync(DeleteAndUpdateStockByStockAttributesRequest DeleteAndUpdateStockByStockAttributesRequest, object userState) {
            if ((this.DeleteAndUpdateStockByStockAttributesOperationCompleted == null)) {
                this.DeleteAndUpdateStockByStockAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAndUpdateStockByStockAttributesOperationCompleted);
            }
            this.InvokeAsync("DeleteAndUpdateStockByStockAttributes", new object[] {
                        DeleteAndUpdateStockByStockAttributesRequest}, this.DeleteAndUpdateStockByStockAttributesOperationCompleted, userState);
        }
        
        private void OnDeleteAndUpdateStockByStockAttributesOperationCompleted(object arg) {
            if ((this.DeleteAndUpdateStockByStockAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAndUpdateStockByStockAttributesCompleted(this, new DeleteAndUpdateStockByStockAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductIdRequest {
        
        private Authentication authField;
        
        private long productIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForUpdateStockWithAttributes {
        
        private StockAttribute[] attributesField;
        
        private string quantityField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockAttribute {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductWithIdAndStockAttributesForUpdate {
        
        private long idField;
        
        private StockItemForUpdateStockWithAttributes[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForUpdateStockWithAttributes[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForUpdateStockWithSellerStockCode {
        
        private string sellerStockCodeField;
        
        private string quantityField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForUpdateStockWithId {
        
        private long idField;
        
        private string quantityField;
        
        private long versionField;
        
        private System.Nullable<bool> delistField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool> delist {
            get {
                return this.delistField;
            }
            set {
                this.delistField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForAddStockWithAttributes {
        
        private StockAttribute[] attributesField;
        
        private string quantityToIncreaseField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantityToIncrease {
            get {
                return this.quantityToIncreaseField;
            }
            set {
                this.quantityToIncreaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductWithIdAndStockAttributes {
        
        private long idField;
        
        private StockItemForAddStockWithAttributes[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForAddStockWithAttributes[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForAddStockWithSellerStockCode {
        
        private string sellerStockCodeField;
        
        private string quantityToIncreaseField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantityToIncrease {
            get {
                return this.quantityToIncreaseField;
            }
            set {
                this.quantityToIncreaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItem {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class StockItemForAddStockWithId {
        
        private long idField;
        
        private string quantityToIncreaseField;
        
        private long versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantityToIncrease {
            get {
                return this.quantityToIncreaseField;
            }
            set {
                this.quantityToIncreaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductAttribute {
        
        private long idField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSkuBasic))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSku))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuBasicRequest {
        
        private string sellerStockCodeField;
        
        private decimal optionPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sellerStockCode {
            get {
                return this.sellerStockCodeField;
            }
            set {
                this.sellerStockCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal optionPrice {
            get {
                return this.optionPriceField;
            }
            set {
                this.optionPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSku))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSkuBasic : ProductSkuBasicRequest {
        
        private decimal currencyAmountField;
        
        private decimal displayPriceField;
        
        private decimal oldOptionPriceField;
        
        private string gtinField;
        
        private string mpnField;
        
        private bool bundleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal currencyAmount {
            get {
                return this.currencyAmountField;
            }
            set {
                this.currencyAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal displayPrice {
            get {
                return this.displayPriceField;
            }
            set {
                this.displayPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal oldOptionPrice {
            get {
                return this.oldOptionPriceField;
            }
            set {
                this.oldOptionPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mpn {
            get {
                return this.mpnField;
            }
            set {
                this.mpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool bundle {
            get {
                return this.bundleField;
            }
            set {
                this.bundleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ProductSku : ProductSkuBasic {
        
        private long idField;
        
        private long versionField;
        
        private string quantityField;
        
        private ProductAttribute[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductIdResponse {
        
        private ResultInfo resultField;
        
        private ProductSku[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductSku[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductSellerCodeRequest {
        
        private Authentication authField;
        
        private string productSellerCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productSellerCode {
            get {
                return this.productSellerCodeField;
            }
            set {
                this.productSellerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetProductStockByProductSellerCodeResponse {
        
        private ResultInfo resultField;
        
        private ProductSku[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProductSku[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockIdRequest {
        
        private Authentication authField;
        
        private StockItemForAddStockWithId[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForAddStockWithId[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockIdResponse {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockSellerCodeRequest {
        
        private Authentication authField;
        
        private StockItemForAddStockWithSellerStockCode[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForAddStockWithSellerStockCode[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockSellerCodeResponse {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockAttributesRequest {
        
        private Authentication authField;
        
        private ProductWithIdAndStockAttributes productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductWithIdAndStockAttributes product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class IncreaseStockByStockAttributesResponse {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockIdRequest {
        
        private Authentication authField;
        
        private StockItemForUpdateStockWithId[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForUpdateStockWithId[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockIdResponse {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockSellerCodeRequest {
        
        private Authentication authField;
        
        private StockItemForUpdateStockWithSellerStockCode[] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItemForUpdateStockWithSellerStockCode[] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class UpdateStockByStockSellerCodeResponse {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class DeleteAndUpdateStockByStockAttributesRequest {
        
        private Authentication authField;
        
        private ProductWithIdAndStockAttributesForUpdate productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductWithIdAndStockAttributesForUpdate product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class DeleteAndUpdateStockByStockAttributesResponse {
        
        private ResultInfo resultField;
        
        private StockItem[][] stockItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stockItem", typeof(StockItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public StockItem[][] stockItems {
            get {
                return this.stockItemsField;
            }
            set {
                this.stockItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetProductStockByProductIdCompletedEventHandler(object sender, GetProductStockByProductIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductStockByProductIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductStockByProductIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProductStockByProductIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProductStockByProductIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetProductStockByProductSellerCodeCompletedEventHandler(object sender, GetProductStockByProductSellerCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductStockByProductSellerCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductStockByProductSellerCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProductStockByProductSellerCodeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProductStockByProductSellerCodeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IncreaseStockByStockIdCompletedEventHandler(object sender, IncreaseStockByStockIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncreaseStockByStockIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncreaseStockByStockIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncreaseStockByStockIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncreaseStockByStockIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IncreaseStockByStockSellerCodeCompletedEventHandler(object sender, IncreaseStockByStockSellerCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncreaseStockByStockSellerCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncreaseStockByStockSellerCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncreaseStockByStockSellerCodeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncreaseStockByStockSellerCodeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IncreaseStockByStockAttributesCompletedEventHandler(object sender, IncreaseStockByStockAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncreaseStockByStockAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncreaseStockByStockAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncreaseStockByStockAttributesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncreaseStockByStockAttributesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateStockByStockIdCompletedEventHandler(object sender, UpdateStockByStockIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStockByStockIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStockByStockIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateStockByStockIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateStockByStockIdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateStockByStockSellerCodeCompletedEventHandler(object sender, UpdateStockByStockSellerCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStockByStockSellerCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStockByStockSellerCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateStockByStockSellerCodeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateStockByStockSellerCodeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DeleteAndUpdateStockByStockAttributesCompletedEventHandler(object sender, DeleteAndUpdateStockByStockAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAndUpdateStockByStockAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAndUpdateStockByStockAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteAndUpdateStockByStockAttributesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteAndUpdateStockByStockAttributesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591