//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aresv2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.n11.com/ws/schemas", ConfigurationName="ServiceReference1.CategoryServicePort")]
    public interface CategoryServicePort {
        
        // CODEGEN: Generating message contract since the operation GetCategoryAttributes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aresv2.ServiceReference1.GetCategoryAttributesResponse1 GetCategoryAttributes(Aresv2.ServiceReference1.GetCategoryAttributesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributesResponse1> GetCategoryAttributesAsync(Aresv2.ServiceReference1.GetCategoryAttributesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetParentCategory is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aresv2.ServiceReference1.GetParentCategoryResponse1 GetParentCategory(Aresv2.ServiceReference1.GetParentCategoryRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetParentCategoryResponse1> GetParentCategoryAsync(Aresv2.ServiceReference1.GetParentCategoryRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetSubCategories is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aresv2.ServiceReference1.GetSubCategoriesResponse1 GetSubCategories(Aresv2.ServiceReference1.GetSubCategoriesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetSubCategoriesResponse1> GetSubCategoriesAsync(Aresv2.ServiceReference1.GetSubCategoriesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetCategoryAttributesId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aresv2.ServiceReference1.GetCategoryAttributesIdResponse1 GetCategoryAttributesId(Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributesIdResponse1> GetCategoryAttributesIdAsync(Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetTopLevelCategories is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aresv2.ServiceReference1.GetTopLevelCategoriesResponse1 GetTopLevelCategories(Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetTopLevelCategoriesResponse1> GetTopLevelCategoriesAsync(Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetCategoryAttributeValue is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Aresv2.ServiceReference1.GetCategoryAttributeValueResponse1 GetCategoryAttributeValue(Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributeValueResponse1> GetCategoryAttributeValueAsync(Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCategoryAttributesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long categoryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("categoryId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appKeyField;
        
        private string appSecretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appSecret {
            get {
                return this.appSecretField;
            }
            set {
                this.appSecretField = value;
                this.RaisePropertyChanged("appSecret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class CategoryProductAttributeValueData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string dependedNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string dependedName {
            get {
                return this.dependedNameField;
            }
            set {
                this.dependedNameField = value;
                this.RaisePropertyChanged("dependedName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class RequestPagingData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> currentPageField;
        
        private System.Nullable<int> pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class CategoryProductAttributeData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private bool mandatoryField;
        
        private bool multipleSelectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
                this.RaisePropertyChanged("mandatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool multipleSelect {
            get {
                return this.multipleSelectField;
            }
            set {
                this.multipleSelectField = value;
                this.RaisePropertyChanged("multipleSelect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class SubCategoryData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private SubCategory[] subCategoryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("subCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SubCategory[] subCategoryList {
            get {
                return this.subCategoryListField;
            }
            set {
                this.subCategoryListField = value;
                this.RaisePropertyChanged("subCategoryList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class SubCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ParentCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ParentCategoryData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private ParentCategory parentCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ParentCategory parentCategory {
            get {
                return this.parentCategoryField;
            }
            set {
                this.parentCategoryField = value;
                this.RaisePropertyChanged("parentCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class CategoryAttributeValueData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string dependedNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string dependedName {
            get {
                return this.dependedNameField;
            }
            set {
                this.dependedNameField = value;
                this.RaisePropertyChanged("dependedName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class CategoryAttributeData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private bool mandatoryField;
        
        private bool multipleSelectField;
        
        private CategoryAttributeValueData[] valueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool mandatory {
            get {
                return this.mandatoryField;
            }
            set {
                this.mandatoryField = value;
                this.RaisePropertyChanged("mandatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool multipleSelect {
            get {
                return this.multipleSelectField;
            }
            set {
                this.multipleSelectField = value;
                this.RaisePropertyChanged("multipleSelect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CategoryAttributeValueData[] valueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
                this.RaisePropertyChanged("valueList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class CategoryData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private CategoryData parentCategoryField;
        
        private SubCategory[] subCategoryListField;
        
        private CategoryAttributeData[] attributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public CategoryData parentCategory {
            get {
                return this.parentCategoryField;
            }
            set {
                this.parentCategoryField = value;
                this.RaisePropertyChanged("parentCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("subCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SubCategory[] subCategoryList {
            get {
                return this.subCategoryListField;
            }
            set {
                this.subCategoryListField = value;
                this.RaisePropertyChanged("subCategoryList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CategoryAttributeData[] attributeList {
            get {
                return this.attributeListField;
            }
            set {
                this.attributeListField = value;
                this.RaisePropertyChanged("attributeList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.n11.com/ws/schemas")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorCategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string errorCategory {
            get {
                return this.errorCategoryField;
            }
            set {
                this.errorCategoryField = value;
                this.RaisePropertyChanged("errorCategory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCategoryAttributesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private CategoryData categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CategoryData category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryAttributesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetCategoryAttributesRequest GetCategoryAttributesRequest;
        
        public GetCategoryAttributesRequest1() {
        }
        
        public GetCategoryAttributesRequest1(Aresv2.ServiceReference1.GetCategoryAttributesRequest GetCategoryAttributesRequest) {
            this.GetCategoryAttributesRequest = GetCategoryAttributesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryAttributesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetCategoryAttributesResponse GetCategoryAttributesResponse;
        
        public GetCategoryAttributesResponse1() {
        }
        
        public GetCategoryAttributesResponse1(Aresv2.ServiceReference1.GetCategoryAttributesResponse GetCategoryAttributesResponse) {
            this.GetCategoryAttributesResponse = GetCategoryAttributesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetParentCategoryRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long categoryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("categoryId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetParentCategoryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private ParentCategoryData categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ParentCategoryData category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParentCategoryRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetParentCategoryRequest GetParentCategoryRequest;
        
        public GetParentCategoryRequest1() {
        }
        
        public GetParentCategoryRequest1(Aresv2.ServiceReference1.GetParentCategoryRequest GetParentCategoryRequest) {
            this.GetParentCategoryRequest = GetParentCategoryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetParentCategoryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetParentCategoryResponse GetParentCategoryResponse;
        
        public GetParentCategoryResponse1() {
        }
        
        public GetParentCategoryResponse1(Aresv2.ServiceReference1.GetParentCategoryResponse GetParentCategoryResponse) {
            this.GetParentCategoryResponse = GetParentCategoryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetSubCategoriesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long categoryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("categoryId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetSubCategoriesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private SubCategoryData[] categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public SubCategoryData[] category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubCategoriesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetSubCategoriesRequest GetSubCategoriesRequest;
        
        public GetSubCategoriesRequest1() {
        }
        
        public GetSubCategoriesRequest1(Aresv2.ServiceReference1.GetSubCategoriesRequest GetSubCategoriesRequest) {
            this.GetSubCategoriesRequest = GetSubCategoriesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubCategoriesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetSubCategoriesResponse GetSubCategoriesResponse;
        
        public GetSubCategoriesResponse1() {
        }
        
        public GetSubCategoriesResponse1(Aresv2.ServiceReference1.GetSubCategoriesResponse GetSubCategoriesResponse) {
            this.GetSubCategoriesResponse = GetSubCategoriesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCategoryAttributesIdRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long categoryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("categoryId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCategoryAttributesIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private CategoryProductAttributeData[] categoryProductAttributeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("categoryProductAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CategoryProductAttributeData[] categoryProductAttributeList {
            get {
                return this.categoryProductAttributeListField;
            }
            set {
                this.categoryProductAttributeListField = value;
                this.RaisePropertyChanged("categoryProductAttributeList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryAttributesIdRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetCategoryAttributesIdRequest GetCategoryAttributesIdRequest;
        
        public GetCategoryAttributesIdRequest1() {
        }
        
        public GetCategoryAttributesIdRequest1(Aresv2.ServiceReference1.GetCategoryAttributesIdRequest GetCategoryAttributesIdRequest) {
            this.GetCategoryAttributesIdRequest = GetCategoryAttributesIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryAttributesIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetCategoryAttributesIdResponse GetCategoryAttributesIdResponse;
        
        public GetCategoryAttributesIdResponse1() {
        }
        
        public GetCategoryAttributesIdResponse1(Aresv2.ServiceReference1.GetCategoryAttributesIdResponse GetCategoryAttributesIdResponse) {
            this.GetCategoryAttributesIdResponse = GetCategoryAttributesIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetTopLevelCategoriesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetTopLevelCategoriesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private SubCategory[] categoryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public SubCategory[] categoryList {
            get {
                return this.categoryListField;
            }
            set {
                this.categoryListField = value;
                this.RaisePropertyChanged("categoryList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopLevelCategoriesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetTopLevelCategoriesRequest GetTopLevelCategoriesRequest;
        
        public GetTopLevelCategoriesRequest1() {
        }
        
        public GetTopLevelCategoriesRequest1(Aresv2.ServiceReference1.GetTopLevelCategoriesRequest GetTopLevelCategoriesRequest) {
            this.GetTopLevelCategoriesRequest = GetTopLevelCategoriesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopLevelCategoriesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetTopLevelCategoriesResponse GetTopLevelCategoriesResponse;
        
        public GetTopLevelCategoriesResponse1() {
        }
        
        public GetTopLevelCategoriesResponse1(Aresv2.ServiceReference1.GetTopLevelCategoriesResponse GetTopLevelCategoriesResponse) {
            this.GetTopLevelCategoriesResponse = GetTopLevelCategoriesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCategoryAttributeValueRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Authentication authField;
        
        private long categoryProductAttributeIdField;
        
        private RequestPagingData pagingDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Authentication auth {
            get {
                return this.authField;
            }
            set {
                this.authField = value;
                this.RaisePropertyChanged("auth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long categoryProductAttributeId {
            get {
                return this.categoryProductAttributeIdField;
            }
            set {
                this.categoryProductAttributeIdField = value;
                this.RaisePropertyChanged("categoryProductAttributeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RequestPagingData pagingData {
            get {
                return this.pagingDataField;
            }
            set {
                this.pagingDataField = value;
                this.RaisePropertyChanged("pagingData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.n11.com/ws/schemas")]
    public partial class GetCategoryAttributeValueResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultInfo resultField;
        
        private CategoryProductAttributeValueData[] categoryProductAttributeValueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultInfo result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("categoryProductAttributeValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CategoryProductAttributeValueData[] categoryProductAttributeValueList {
            get {
                return this.categoryProductAttributeValueListField;
            }
            set {
                this.categoryProductAttributeValueListField = value;
                this.RaisePropertyChanged("categoryProductAttributeValueList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryAttributeValueRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetCategoryAttributeValueRequest GetCategoryAttributeValueRequest;
        
        public GetCategoryAttributeValueRequest1() {
        }
        
        public GetCategoryAttributeValueRequest1(Aresv2.ServiceReference1.GetCategoryAttributeValueRequest GetCategoryAttributeValueRequest) {
            this.GetCategoryAttributeValueRequest = GetCategoryAttributeValueRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryAttributeValueResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.n11.com/ws/schemas", Order=0)]
        public Aresv2.ServiceReference1.GetCategoryAttributeValueResponse GetCategoryAttributeValueResponse;
        
        public GetCategoryAttributeValueResponse1() {
        }
        
        public GetCategoryAttributeValueResponse1(Aresv2.ServiceReference1.GetCategoryAttributeValueResponse GetCategoryAttributeValueResponse) {
            this.GetCategoryAttributeValueResponse = GetCategoryAttributeValueResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoryServicePortChannel : Aresv2.ServiceReference1.CategoryServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryServicePortClient : System.ServiceModel.ClientBase<Aresv2.ServiceReference1.CategoryServicePort>, Aresv2.ServiceReference1.CategoryServicePort {
        
        public CategoryServicePortClient() {
        }
        
        public CategoryServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aresv2.ServiceReference1.GetCategoryAttributesResponse1 Aresv2.ServiceReference1.CategoryServicePort.GetCategoryAttributes(Aresv2.ServiceReference1.GetCategoryAttributesRequest1 request) {
            return base.Channel.GetCategoryAttributes(request);
        }
        
        public Aresv2.ServiceReference1.GetCategoryAttributesResponse GetCategoryAttributes(Aresv2.ServiceReference1.GetCategoryAttributesRequest GetCategoryAttributesRequest) {
            Aresv2.ServiceReference1.GetCategoryAttributesRequest1 inValue = new Aresv2.ServiceReference1.GetCategoryAttributesRequest1();
            inValue.GetCategoryAttributesRequest = GetCategoryAttributesRequest;
            Aresv2.ServiceReference1.GetCategoryAttributesResponse1 retVal = ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetCategoryAttributes(inValue);
            return retVal.GetCategoryAttributesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributesResponse1> Aresv2.ServiceReference1.CategoryServicePort.GetCategoryAttributesAsync(Aresv2.ServiceReference1.GetCategoryAttributesRequest1 request) {
            return base.Channel.GetCategoryAttributesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributesResponse1> GetCategoryAttributesAsync(Aresv2.ServiceReference1.GetCategoryAttributesRequest GetCategoryAttributesRequest) {
            Aresv2.ServiceReference1.GetCategoryAttributesRequest1 inValue = new Aresv2.ServiceReference1.GetCategoryAttributesRequest1();
            inValue.GetCategoryAttributesRequest = GetCategoryAttributesRequest;
            return ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetCategoryAttributesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aresv2.ServiceReference1.GetParentCategoryResponse1 Aresv2.ServiceReference1.CategoryServicePort.GetParentCategory(Aresv2.ServiceReference1.GetParentCategoryRequest1 request) {
            return base.Channel.GetParentCategory(request);
        }
        
        public Aresv2.ServiceReference1.GetParentCategoryResponse GetParentCategory(Aresv2.ServiceReference1.GetParentCategoryRequest GetParentCategoryRequest) {
            Aresv2.ServiceReference1.GetParentCategoryRequest1 inValue = new Aresv2.ServiceReference1.GetParentCategoryRequest1();
            inValue.GetParentCategoryRequest = GetParentCategoryRequest;
            Aresv2.ServiceReference1.GetParentCategoryResponse1 retVal = ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetParentCategory(inValue);
            return retVal.GetParentCategoryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetParentCategoryResponse1> Aresv2.ServiceReference1.CategoryServicePort.GetParentCategoryAsync(Aresv2.ServiceReference1.GetParentCategoryRequest1 request) {
            return base.Channel.GetParentCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetParentCategoryResponse1> GetParentCategoryAsync(Aresv2.ServiceReference1.GetParentCategoryRequest GetParentCategoryRequest) {
            Aresv2.ServiceReference1.GetParentCategoryRequest1 inValue = new Aresv2.ServiceReference1.GetParentCategoryRequest1();
            inValue.GetParentCategoryRequest = GetParentCategoryRequest;
            return ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetParentCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aresv2.ServiceReference1.GetSubCategoriesResponse1 Aresv2.ServiceReference1.CategoryServicePort.GetSubCategories(Aresv2.ServiceReference1.GetSubCategoriesRequest1 request) {
            return base.Channel.GetSubCategories(request);
        }
        
        public Aresv2.ServiceReference1.GetSubCategoriesResponse GetSubCategories(Aresv2.ServiceReference1.GetSubCategoriesRequest GetSubCategoriesRequest) {
            Aresv2.ServiceReference1.GetSubCategoriesRequest1 inValue = new Aresv2.ServiceReference1.GetSubCategoriesRequest1();
            inValue.GetSubCategoriesRequest = GetSubCategoriesRequest;
            Aresv2.ServiceReference1.GetSubCategoriesResponse1 retVal = ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetSubCategories(inValue);
            return retVal.GetSubCategoriesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetSubCategoriesResponse1> Aresv2.ServiceReference1.CategoryServicePort.GetSubCategoriesAsync(Aresv2.ServiceReference1.GetSubCategoriesRequest1 request) {
            return base.Channel.GetSubCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetSubCategoriesResponse1> GetSubCategoriesAsync(Aresv2.ServiceReference1.GetSubCategoriesRequest GetSubCategoriesRequest) {
            Aresv2.ServiceReference1.GetSubCategoriesRequest1 inValue = new Aresv2.ServiceReference1.GetSubCategoriesRequest1();
            inValue.GetSubCategoriesRequest = GetSubCategoriesRequest;
            return ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetSubCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aresv2.ServiceReference1.GetCategoryAttributesIdResponse1 Aresv2.ServiceReference1.CategoryServicePort.GetCategoryAttributesId(Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1 request) {
            return base.Channel.GetCategoryAttributesId(request);
        }
        
        public Aresv2.ServiceReference1.GetCategoryAttributesIdResponse GetCategoryAttributesId(Aresv2.ServiceReference1.GetCategoryAttributesIdRequest GetCategoryAttributesIdRequest) {
            Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1 inValue = new Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1();
            inValue.GetCategoryAttributesIdRequest = GetCategoryAttributesIdRequest;
            Aresv2.ServiceReference1.GetCategoryAttributesIdResponse1 retVal = ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetCategoryAttributesId(inValue);
            return retVal.GetCategoryAttributesIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributesIdResponse1> Aresv2.ServiceReference1.CategoryServicePort.GetCategoryAttributesIdAsync(Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1 request) {
            return base.Channel.GetCategoryAttributesIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributesIdResponse1> GetCategoryAttributesIdAsync(Aresv2.ServiceReference1.GetCategoryAttributesIdRequest GetCategoryAttributesIdRequest) {
            Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1 inValue = new Aresv2.ServiceReference1.GetCategoryAttributesIdRequest1();
            inValue.GetCategoryAttributesIdRequest = GetCategoryAttributesIdRequest;
            return ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetCategoryAttributesIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aresv2.ServiceReference1.GetTopLevelCategoriesResponse1 Aresv2.ServiceReference1.CategoryServicePort.GetTopLevelCategories(Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1 request) {
            return base.Channel.GetTopLevelCategories(request);
        }
        
        public Aresv2.ServiceReference1.GetTopLevelCategoriesResponse GetTopLevelCategories(Aresv2.ServiceReference1.GetTopLevelCategoriesRequest GetTopLevelCategoriesRequest) {
            Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1 inValue = new Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1();
            inValue.GetTopLevelCategoriesRequest = GetTopLevelCategoriesRequest;
            Aresv2.ServiceReference1.GetTopLevelCategoriesResponse1 retVal = ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetTopLevelCategories(inValue);
            return retVal.GetTopLevelCategoriesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetTopLevelCategoriesResponse1> Aresv2.ServiceReference1.CategoryServicePort.GetTopLevelCategoriesAsync(Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1 request) {
            return base.Channel.GetTopLevelCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetTopLevelCategoriesResponse1> GetTopLevelCategoriesAsync(Aresv2.ServiceReference1.GetTopLevelCategoriesRequest GetTopLevelCategoriesRequest) {
            Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1 inValue = new Aresv2.ServiceReference1.GetTopLevelCategoriesRequest1();
            inValue.GetTopLevelCategoriesRequest = GetTopLevelCategoriesRequest;
            return ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetTopLevelCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aresv2.ServiceReference1.GetCategoryAttributeValueResponse1 Aresv2.ServiceReference1.CategoryServicePort.GetCategoryAttributeValue(Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1 request) {
            return base.Channel.GetCategoryAttributeValue(request);
        }
        
        public Aresv2.ServiceReference1.GetCategoryAttributeValueResponse GetCategoryAttributeValue(Aresv2.ServiceReference1.GetCategoryAttributeValueRequest GetCategoryAttributeValueRequest) {
            Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1 inValue = new Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1();
            inValue.GetCategoryAttributeValueRequest = GetCategoryAttributeValueRequest;
            Aresv2.ServiceReference1.GetCategoryAttributeValueResponse1 retVal = ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetCategoryAttributeValue(inValue);
            return retVal.GetCategoryAttributeValueResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributeValueResponse1> Aresv2.ServiceReference1.CategoryServicePort.GetCategoryAttributeValueAsync(Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1 request) {
            return base.Channel.GetCategoryAttributeValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aresv2.ServiceReference1.GetCategoryAttributeValueResponse1> GetCategoryAttributeValueAsync(Aresv2.ServiceReference1.GetCategoryAttributeValueRequest GetCategoryAttributeValueRequest) {
            Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1 inValue = new Aresv2.ServiceReference1.GetCategoryAttributeValueRequest1();
            inValue.GetCategoryAttributeValueRequest = GetCategoryAttributeValueRequest;
            return ((Aresv2.ServiceReference1.CategoryServicePort)(this)).GetCategoryAttributeValueAsync(inValue);
        }
    }
}
